name: Wicked Rainman
permalink: /blog/:year/:month/:day/:title
permalink: /task/:year/:month/:day/:title
markdown: kramdown
theme: jekyll-theme-cayman
title: Welcome to Wicked Rainman's home page
description: Feel free to browse!
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
